version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123Mudar!
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "sqlcmd -U sa -P 123Mudar! -Q 'select 1'" ]
      interval: 20s
      timeout: 10s
      retries: 20

  api:
    build:
      context: .
      dockerfile: src/TaskManager.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TaskManagerDb;User Id=sa;Password=123Mudar!;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy